export const PAGE_CHANGED = "PAGE_CHANGED";
export const SEARCH_EXPAND_TOGGLED = "SEARCH_EXPAND_TOGGLED"
export const SEARCH_FILTER_ADDED = "SEARCH_FILTER_ADDED"
export const SEARCH_FILTER_REMOVED = "SEARCH_FILTER_REMOVED"
export const SEARCH_ALL_FILTERS_REMOVED = "SEARCH_ALL_FILTERS_REMOVED"
export const FAVORITE_ADDED = "FAVORITE_ADDED"
export const FAVORITE_REMOVED = "FAVORITE_REMOVED"
export const RANK_CHANGED = "RANK_CHANGED"